### PR TITLE
updated to support rails 5.2

### PR DESCRIPTION
**Pull request by urkle**

### CODE REVIEW

**Comment by urkle** [comment]
@ronen @lowjoel this is the PR to add Rails 5.1 + 5.2 support.  It is derived off the work in PR #13 but retains 4.2 support for now. And more cleanly handles the "bigint" vs "integer" fun that 5.1 introduces.

we can do a different major bump later that removes 4.x support for all of the gems in one-go.

**Review by lowjoel — APPROVED** [review]
I've only done a static review of the code, if you've tested it on a live app, this is good!

**Review by ronen — APPROVED** [review]

**Comment by ronen** [comment]
@urkle, do you want to go ahead and merge & release this?  I would, but we may as well verify that it works for you to do it...

**Comment by urkle** [comment]
@ronen ooh.. I have rubygems access..  yeah.. I'll test my hand at merge+release.

**Comment by urkle** [comment]
@ronen release pushed to rubygems

**Pull request merged**
