### PR TITLE
Add support for Rails 5.1

### PR DESCRIPTION
**Pull request by jakobdamjensen**
No big changes really. Just added Gemfiles for Rails 5.1 so it can be tested. We're depending on https://github.com/SchemaPlus/schema_auto_foreign_keys which I would like add rails 5.1 support to also. But before I can do that we need to add it here first (since schema_auto_foreign_keys depend on this gem) :smile:

### CODE REVIEW

**Comment by ronen** [comment]
@jakobdamjensen thanks -- but the tests didn't actually run on 5.1, so still can't be sure whether this really works with 5.1!  The commit doesn't include the corresponding changes to `schema_dev.yml` and `.travis.yml`.  

I don't know if you just didn't commit them, or if you went around the [`schema_dev`](https://github.com/SchemaPlus/schema_dev) mechanism.  If you did, here's the quick instructions:  Update `schema_dev.yml` then run `schema_dev freshen` which in turn will update all the generated stuff: `.travis.yml`, `gemfiles/*`, `README.md` matrixes.  (`schema_dev` will be pulled in by `bundle install`.)

**Comment by jakobdamjensen** [comment]
@ronen Sorry about that. I do see that the mysql specs are failing on 5.1 now :cry: I'll see what I can do about it.

**Comment by ronen** [comment]
@jakobdamjensen no prob, lotsa thanks for looking into it!

**Comment by jakobdamjensen** [comment]
I'll close this PR and try to work on https://github.com/SchemaPlus/schema_plus_foreign_keys/pull/13 instead. Seems to make more sense

**Pull request closed without merging**
